apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: notes-app-prod
data:
  NODE_ENV: "production"
  PORT: "5000"
  DB_HOST: "192.168.1.151"
  DB_PORT: "5432"
  DB_NAME: "NotesApp"
  DB_USER: "postgres"

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: notes-app-prod
type: Opaque
data:
  DB_PASSWORD: Y2hhbmdlbWU=  # base64 encoded 'changeme'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: notes-app-prod
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 192.168.1.150:3000/morris/notes-app-backend:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: backend-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: DB_PASSWORD
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 5

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: notes-app-prod
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30050
  type: NodePort
